#!/bin/bash

RCLONE_REPO="rclone/rclone"
RELEASES=$(curl -qsL https://api.github.com/repos/${RCLONE_REPO}/tags | grep \"name\"|sed "s/^ *\"name\" *: *\"v\(\([0-9]\+\.\)\+[0-9]\+\\)\" *,/\1/g")
latest=$(echo ${RELEASES}|cut -d" " -f1)
docker build --build-arg RCLONE_VERSION=$latest -t ${DOCKER_REPO}:latest .
