#!/usr/bin/with-contenv sh

rclone --version

# convert crlf
tr -d '\r' < /config/rclone_cron > /tmp/rclone_cron

# set crontab
cat /tmp/rclone_cron && echo ""
crontab -u abc /tmp/rclone_cron

# create empty config file
touch /config/rclone.conf

# permissions
chown abc:abc /config/rclone.conf
chmod 777 /var/lock
