#!/usr/bin/with-contenv sh

rclone --version

# set crontab
cat /config/rclone_cron && echo ""
crontab -u abc /config/rclone_cron

# create empty config file
touch /config/rclone.conf

# permissions
chown abc:abc /config/rclone.conf
chmod 777 /var/lock

